#cloud-config
disable_ec2_metadata: true
hostname: ${hostname}
fqdn: ${hostname}.local
manage_etc_hosts: true
fs_setup:
%{ for v in { for k,v in volumes : k=>v if try(v.use_base_volume, false) == false} ~}
  - label: ${v.label}
    filesystem: ${v.fs_type}
    overwrite: ${try(v.wipe, false)}
    device: /dev/disk/by-id/wwn-0x${v.wwn}
%{ endfor ~}
mounts:
# [ fs_spec, fs_file, fs_vfstype, fs_mntops, fs-freq, fs_passno ].
%{ for v in { for k,v in volumes : k=>v if try(v.use_base_volume, false) == false} ~}
  - ["LABEL=${v.label}", "${v.mount}", "${v.fs_type}"]
%{ endfor ~}
users:
  - name: root
    ssh_authorized_keys: ${jsonencode(ssh_keys)}