hypervisor_defaults:
  uri: qemu:///system
  local_networks:
    - name: isolated
      addresses: "192.168.201.0/24"
        #- "2001:db8:ca2:2::1/64"
      dhcp4_range: "10-200"
      dhcp4: true
      static: true
      mode: route
#    - name: management
#      create: false

storage_pools_defaults:
  pool:
    name: default
    prefix: /var/lib/libvirt

luks_keys:
  luks-etcd:
    length: 128
    filename: /etc/pki/luks-etcd.key

network_defaults:
  addresses: [ ]
  dhcp4: false
  dhcp4_range: "2-254"
  dhcp6: false
  static: false
  mtu: 1500
  mode: none
  create: true
  autostart: true

# this needs to match the VM roles
volumes_defaults:
  master:
    - name: root
      mount: /
      size: 100
      wwn: 300000000000b001
      initialize: false
      use_base_volume: true
      fs_type: xfs
      label: root
    - name: containerd
      mount: /var/lib/containerd
      size: 10
      wwn: 3000000000a1eead
      initialize: true
      fs_type: xfs
      label: CONLIB
    - name: run-containerd
      mount: /run/containerd
      size: 10
      wwn: 300000c0e1a1eead
      initialize: true
      fs_type: xfs
      label: CONRUN
    - name: kubelet
      mount: /var/lib/kubelet
      size: 10
      wwn: 300000000c0be1e1
      initialize: true
      fs_type: xfs
      label: K8SLET
  etcd:
    - name: etcd
      mount: /var/lib/etcd
      size: 32
      wwn: 300000000000e1cd
      initialize: false
      fs_type: xfs
      label: ETCDK8S
      pool:
        name: etcd
        prefix: /var/lib/etcd
      luks:
        key: luks-etcd
  worker:
    - name: root
      mount: /
      size: 21
      wwn: 300000000000b001
      initialize: false
      use_base_volume: true
      fs_type: xfs
      label: root
    - name: containerd
      mount: /var/lib/containerd
      size: 10
      wwn: 3000000000a1eead
      initialize: true
      fs_type: xfs
      label: CONLIB
    - name: run-containerd
      mount: /run/containerd
      size: 10
      wwn: 300000c0e1a1eead
      initialize: true
      fs_type: xfs
      label: CONRUN
    - name: kubelet
      mount: /var/lib/kubelet
      size: 10
      wwn: 300000000c0be1e1
      initialize: true
      fs_type: xfs
      label: K8SLET

node_defaults:
  vcpu: 2
  memory: 4096
  network_interfaces: []
  # network_interfaces:
  #   - mode: macvtap
  #     target: enp42s0
  #     mtu: 1500
  #     dhcp4: true
  #     dhcp6: false
  base_volume:
    arch: x86_64
    format: qcow2
    name: kubernetes-vm
    size: 20
    uri: /vms/images
  # ssh keys are also read and merged from ./ssh-keys
  ssh_keys: [ ]

hardware_defaults:
  amd:
    vendor: "0x1002"
    product: "0x73bf"
  sandisk:
    vendor: "0x15b7"
    product: "0x5009"
  realtek:
    vendor: "0x10ec"
    product : "0x8125"
  realtek_net:
    vendor: "0x10ec"
    product: "0x8168"
