# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    libvirt = {
      source  = "dmacvicar/libvirt"
      version = "0.7.1"
    }
  }
}
provider "libvirt" {
  alias = "h001"
  uri = "qemu:///system"
}

module "h001_pool" {
  source = "./modules/storage_pool"
  name = "h001_images"
  providers = {
    libvirt = libvirt.h001
  }
}

module "h001_worker" {
  source        = "./modules/kubernetes"
  name       = "k8s-vm-worker-h001"
  pool          = module.h001_pool.pool
  interfaces    = ["eth0"]
  source_image    = "/vms/images/kubernetes-vm-x86_64.qcow2"
  size = 100
  providers = {
    libvirt = libvirt.h001
  }
}
module "h001_master" {
  source        = "./modules/kubernetes"
  name       = "k8s-vm-master-h001"
  pool          = module.h001_pool.pool
  interfaces    = ["eth0"]
  source_image    = "/vms/images/kubernetes-vm-x86_64.qcow2"
  size = 100
  providers = {
    libvirt = libvirt.h001
  }
}
