= Kubernetes
:toc:
:toclevels: 3
// TODO This entire page needs work, at this time it only has notes Russell Bunch needed to leave for the next person to see.

By default, the development variables in `dev.auto.tfvars` will load.
These should be customized by the developer if their defaults are insufficient.

NOTE: To load production variables, use `--var-file ./prod.tfvars`.
Production variables will cater to expectations (such as interfaces) from a Fawkes hypervisor server..

== Local Development on a workstation

=== Prerequisites

- A clone of this repository
- Terraform
- The Kubernetes VM Image

=== Launching VMs

. Initialize Terraform
+
[source,bash]
----
terraform init
----
. Plan the deployment
+
[source,bash]
----
terraform plan
----

== Deployment on a Fawkes System

=== Prerequisites

- A running Fawkes management VM

=== Launching VMs

. Change into the Terraform root, there should be an existing `.terraform` folder already so `terraform init` is not necessary
+
[source,bash]
----
cd /srv/cray/terraform
----
. Plan the deployment
+
[source,bash]
----
terraform plan -var-file="prod.tfvars"
----
